export { default as Header } from './Header/Header'
export { default as About } from './About/About'
export { default as Experience } from './Experience/Experience'
export { default as Services } from './Services/Services'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'